### ISSUE TITLE
是否可以调整slide的顺序

### ISSUE THREAD

**Issue by hanxuanliang** [CCraster/code-slides#1]
开始以为是根据 `json` 的顺序展示的，调整了之后发现并没有成功。
是使用创建时间做排序还是通过什么其他规则。
希望之后可以自定义 `slide` 顺序

**Comment by CCraster** [comment]
想做拖拽排序的，但是vscode extension treeview 的拖拽api还在提议阶段，无法在正式版的vscode中生效。
所以暴露了json文件的入口，目的就是让用户可以通过改json的方式，改变节点的顺序。
我没有在文档中说清楚，目前**改了json之后需要vscode的窗口reload一下，让插件重新加载一次才会让改后的json生效**。mac可以按“cmd + shift + p”在命令窗口输入“reload window”，就能快捷reload了。这一步的交互我还在思考怎么改比较合适。

顺便问下，要是我在每个slide的右侧加上两个icon，分别表示“上移”和“下移”，加上之前的“修改”和“播放”icon就是4个了。作为用户的角度，你会不会觉得按钮有点多了。

**Comment by CCraster** [comment]
想做拖拽排序的，但是vscode extension treeview 的拖拽api还在提议阶段，无法在正式版的vscode中生效。
所以暴露了json文件的入口，目的就是让用户可以通过改json的方式，改变节点的顺序。
我没有在文档中说清楚，目前**改了json之后需要vscode的窗口reload一下，让插件重新加载一次才会让改后的json生效**。mac可以按“cmd + shift + p”在命令窗口输入“reload window”，找到reload命令运行。这一步的交互我还在思考怎么改比较合适。

顺便问下，要是我在每个slide的右侧加上两个icon，分别表示“上移”和“下移”，加上之前的“修改”和“播放”icon就是4个了。作为用户的角度，你会不会觉得按钮有点多了。

**Comment by CCraster** [comment]
> 开始以为是根据 `json` 的顺序展示的，调整了之后发现并没有成功。
> 是使用创建时间做排序还是通过什么其他规则。
> 希望之后可以自定义 `slide` 顺序

想做拖拽排序的，但是vscode extension treeview 的拖拽api还在提议阶段，无法在正式版的vscode中生效。
所以暴露了json文件的入口，目的就是让用户可以通过改json的方式，改变节点的顺序。
我没有在文档中说清楚，目前改了json之后需要vscode的窗口reload一下，让插件重新加载一次才会让改后的json生效。mac可以按“cmd + shift + p”在命令窗口输入“reload window”，找到reload命令运行。下个版本修改json就会立即生效

顺便问下，要是我在每个slide的右侧加上两个icon，分别表示“上移”和“下移”，加上之前的“修改”和“播放”icon就是4个了。作为用户的角度，你会不会觉得按钮有点多了。

**Comment by CCraster** [comment]
> > 开始以为是根据 `json` 的顺序展示的，调整了之后发现并没有成功。
> > 是使用创建时间做排序还是通过什么其他规则。
> > 希望之后可以自定义 `slide` 顺序
> 
> 想做拖拽排序的，但是vscode extension treeview 的拖拽api还在提议阶段，无法在正式版的vscode中生效。
> 所以暴露了json文件的入口，目的就是让用户可以通过改json的方式，改变节点的顺序。
> 我没有在文档中说清楚，目前改了json之后需要vscode的窗口reload一下，让插件重新加载一次才会让改后的json生效。mac可以按“cmd + shift + p”在命令窗口输入“reload window”，找到reload命令运行。这一步的交互我还在思考怎么改比较合适。
> 
> 顺便问下，要是我在每个slide的右侧加上两个icon，分别表示“上移”和“下移”，加上之前的“修改”和“播放”icon就是4个了。作为用户的角度，你会不会觉得按钮有点多了。

**Comment by hanxuanliang** [comment]
> > 开始以为是根据 `json` 的顺序展示的，调整了之后发现并没有成功。
> > 是使用创建时间做排序还是通过什么其他规则。
> > 希望之后可以自定义 `slide` 顺序
> 
> 想做拖拽排序的，但是vscode extension treeview 的拖拽api还在提议阶段，无法在正式版的vscode中生效。
> 所以暴露了json文件的入口，目的就是让用户可以通过改json的方式，改变节点的顺序。
> 我没有在文档中说清楚，目前改了json之后需要vscode的窗口reload一下，让插件重新加载一次才会让改后的json生效。mac可以按“cmd + shift + p”在命令窗口输入“reload window”，找到reload命令运行。下个版本修改json就会立即生效
> 
> 顺便问下，要是我在每个slide的右侧加上两个icon，分别表示“上移”和“下移”，加上之前的“修改”和“播放”icon就是4个了。作为用户的角度，你会不会觉得按钮有点多了。

确实 button 会多，这个了解了。我 reload 一下，如果目前拖拽无法实现，这种自己修改，感觉也还行。
谢谢作者回复。
整体使用起来很舒服。
